/**
 * Kaldi speech recognition REST API
 * Simple REST interface for posting tasks for non realtime speech recognition
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 /*
  * ServiceStatus.h
  *
  *
  */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ServiceStatus_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ServiceStatus_H_


#include "apiClient/ModelBase.h"


namespace mvshyvk {
namespace kaldi {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  ServiceStatus
	: public ModelBase
{
public:
	ServiceStatus();
	virtual ~ServiceStatus();

	/////////////////////////////////////////////
	/// ModelBase overrides

	void validate() override;

	web::json::value toJson() const override;
	bool fromJson(const web::json::value& json) override;

	void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
	bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

	/////////////////////////////////////////////
	/// ServiceStatus members

	/// <summary>
	/// 
	/// </summary>
	int32_t getWorkersCount() const;
	bool workersCountIsSet() const;
	void unsetworkersCount();

	void setWorkersCount(int32_t value);

	/// <summary>
	/// 
	/// </summary>
	int32_t getQueueDepth() const;
	bool queueDepthIsSet() const;
	void unsetqueueDepth();

	void setQueueDepth(int32_t value);

	/// <summary>
	/// 
	/// </summary>
	int32_t getAvailableQueueSlots() const;
	bool availableQueueSlotsIsSet() const;
	void unsetavailableQueueSlots();

	void setAvailableQueueSlots(int32_t value);


protected:
	int32_t m_workersCount;
	bool m_workersCountIsSet;
	int32_t m_queueDepth;
	bool m_queueDepthIsSet;
	int32_t m_availableQueueSlots;
	bool m_availableQueueSlotsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ServiceStatus_H_ */
