/**
 * Kaldi speech recognition REST API
 * Simple REST interface for posting tasks for non realtime speech recognition
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 /*
  * TaskId.h
  *
  *
  */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TaskId_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TaskId_H_


#include "apiClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace mvshyvk {
namespace kaldi {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  TaskId
	: public ModelBase
{
public:
	TaskId();
	virtual ~TaskId();

	/////////////////////////////////////////////
	/// ModelBase overrides

	void validate() override;

	web::json::value toJson() const override;
	bool fromJson(const web::json::value& json) override;

	void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
	bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

	/////////////////////////////////////////////
	/// TaskId members

	/// <summary>
	/// 
	/// </summary>
	utility::string_t getTaskId() const;
	bool taskIdIsSet() const;
	void unsettaskId();

	void setTaskId(const utility::string_t& value);


protected:
	utility::string_t m_taskId;
	bool m_taskIdIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TaskId_H_ */
