/**
 * Kaldi speech recognition REST API
 * Simple REST interface for posting tasks for non realtime speech recognition
 *
 * The version of the OpenAPI document: 0.9.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 /*
  * TaskApi.h
  *
  *
  */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_TaskApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_TaskApi_H_



#include "apiClient/ApiClient.h"
#include "apiClient/HttpContent.h"
#include "Result.h"
#include "TaskId.h"

#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace mvshyvk {
namespace kaldi {
namespace client {
namespace api {

using namespace mvshyvk::kaldi::client::model;



class  TaskApi
{
public:

	explicit TaskApi(std::shared_ptr<const ApiClient> apiClient);

	virtual ~TaskApi();

	/// <summary>
	/// 
	/// </summary>
	/// <remarks>
	/// Adds a task for speach recognition into processing queue
	/// </remarks>
	/// <param name="body"> (optional)</param>
	pplx::task<std::shared_ptr<TaskId>> taskPost(
		boost::optional<std::shared_ptr<HttpContent>> body
	) const;
	/// <summary>
	/// 
	/// </summary>
	/// <remarks>
	/// Retrieves task execution status
	/// </remarks>
	/// <param name="taskId">Task Id to retrieve task execution status</param>
	pplx::task<std::pair<std::shared_ptr<Result>, web::http::status_code>> taskTaskIdStatusGet(
		utility::string_t taskId
	) const;

protected:
	std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_TaskApi_H_ */

